Team-EYAGI/Front

- public/index.html
- src/components/AudioBookList.js
- src/components/Header.js
- src/components/RequestList.js
- src/pages/BookDetail.js
- src/pages/RequestWrite.js
- src/redux/modules/audio.js
- src/redux/modules/user.js
- src/shared/App.js
> 로그인 유지 및 오디오북 요청 CRUD 구현 완료

- package.json
- src/components/AudioBookList.js
- src/components/Header.js
- src/components/MyPageAudioBook.js
- src/pages/AudioModal.js
- src/pages/AudioPlay.js
- src/pages/AudioWrite.js
- src/pages/BookDetail.js
- src/pages/MyPage.js
- src/pages/Request.js
- src/pages/RequestWrite.js
- src/redux/modules/audio.js
- src/redux/modules/book.js
- src/redux/modules/user.js
- src/shared/App.js
- src/styles/modal.css
- yarn.lock
> audio 미리듣기, 목록 재생 구현 완료

- src/components/MainBookList.js
- src/components/MainCategoryBookList.js
- src/pages/Main.js
- src/redux/modules/book.js
> 검색기능, 메인 겟 성공

- src/pages/AddProfileVoice.js
- src/pages/AudioWrite.js
- src/pages/Loading.js
- src/pages/MyPage.js
- src/redux/modules/mypage.js
- src/shared/App.js
> 렌더링시 플레이어 자동재생 문제 해결

- src/components/Header.js
- src/pages/MyPage.js
> admin 페이지 바로가기 생성

- package.json
- src/components/AudioBookList.js
- src/components/BookCard.js
- src/components/MainBookList.js
- src/components/MainCategoryBookCard.js
- src/components/MainCategoryBookList.js
- src/components/MainFundingList.js
- src/components/MainSellerCard.js
- src/components/RequestList.js
- src/elements/Image.js
- src/pages/AddProfileVoice.js
- src/pages/AudioModal.js
- src/pages/AudioPlay.js
- src/pages/AudioWrite.js
- src/pages/Book.js
- src/pages/LoadingPage.js
- src/pages/MyPage.js
- src/pages/ProfileEdit.js
- src/pages/Request.js
- src/pages/SellerProfile.js
- src/redux/modules/audio.js
- src/redux/modules/book.js
- src/redux/modules/creator.js
- src/shared/App.js
- src/shared/InfinityScroll.js
- yarn.lock
> 팔로우, 셀러페이지 수정

- package.json
- src/components/AudioBookList.js
- src/components/AudioReview.js
- src/components/Header.js
- src/components/MyPageAudioBook.js
- src/components/RequestList.js
- src/pages/AddProfileVoice.js
- src/pages/AudioModal.js
- src/pages/AudioPlay.js
- src/pages/AudioWrite.js
- src/pages/BookDetail.js
- src/pages/Loading.js
- src/pages/ProfileEdit.js
- src/pages/RequestWrite.js
- src/pages/ReviewWrite.js
- src/redux/modules/mypage.js
- src/shared/App.js
- src/shared/ScrollToTop.js
- yarn.lock
> sweetAlert 추가

- src/components/FundingCard.js
- src/components/FundingCardList.js
- src/components/Like.js
- src/pages/FundingDetail.js
- src/pages/FundingLoading.js
- src/pages/FundingWrite.js
- src/pages/LogIn.js
- src/pages/SignUp.js
- src/redux/modules/fund.js
- src/shared/Commons.js
> 펀딩 상세페이지 추가

- src/components/FundingCard.js
- src/components/FundingCardList.js
- src/pages/FundingWrite.js
- src/redux/modules/fund.js
> 펀딩 좋아요 수정중

- src/components/Header.js
- src/components/MainFundingCard.js
- src/components/MainFundingList.js
- src/components/MyPageAudioBook.js
- src/components/SearchSellerCard.js
- src/elements/SpeedDial.js
- src/pages/LogIn.js
- src/pages/Main.js
- src/pages/MyPage.js
- src/pages/ProfileEdit.js
- src/pages/Search.js
- src/pages/SellerProfile.js
- src/pages/SignUp.js
- src/redux/modules/book.js
- src/redux/modules/mypage.js
- src/redux/modules/user.js
- src/shared/App.js
- src/styles/slide.css
> top scroll, speedDial 구현

- src/components/Like.js
- src/pages/FundingDetail.js
- src/pages/FundingWrite.js
> 펀딩상세페이지 작업중

- src/components/MyPageAudioBook.js
- src/pages/MyPage.js
- src/pages/SellerProfile.js
> 셀러페이지 오디오 추가

- src/redux/modules/mypage.js
> kakaologin 빌드

- src/pages/KakaoAuthHandler.js
- src/redux/modules/user.js
- src/shared/App.js
> 카카오로그인 url 변경

- src/shared/App.js
> kakao login 재시도

- src/pages/FundingDetail.js
> 내 오디오 등록하기

- public/index.html
- src/components/AudioBookList.js
- src/elements/Image.js
- src/pages/AudioPlay.js
- src/pages/SellerProfile.js
- src/redux/modules/audio.js
- src/redux/modules/creator.js
- src/shared/Pagination.js
> 채팅 및 페이지네이션 수정

- src/elements/SpeedDial.js
> 비로그인 채팅창 진입 차단

- src/pages/AudioPlay.js
- src/pages/FundingDetail.js
- src/pages/MyPage.js
- src/redux/modules/mypage.js
> 크리에이터 페이지 주석 풀기

- README.md
> read me 추가

- README.md
> read me 수정

- README.md
> read me 수정2

- README.md
- src/pages/MyPage.js
- src/redux/modules/mypage.js
> SWR 작업중 및 readme 수정

- src/components/SearchBookCard.js
> 검색 도서 사이즈 맞춤

- src/pages/MyPage.js
> SWR 조건부 데이터 get

- src/components/MainBookList.js
- src/components/MainCategoryBookList.js
- src/components/MainFundingList.js
- src/components/MainSellerList.js
- src/shared/App.js
> SWR ERROR 문구 수정

- src/shared/App.js
> lazy loading

- README.md
> README 상장 추가
